# https is needed !
baseURL = "https://lorenzoinvidia.github.io/"
languageCode = "en-us"
title = "Home"
theme = "hello-friend-ng"
publishDir = "docs"

[params]
homeSubtitle = "Red Teaming & Security Research"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = true

# Enable sharing buttons, if you linke
enableSharingButtons = false

# Metadata mostly used in document's head
description = "Red Teaming & Security Research"
keywords = ""
images = [""]

# Default theme "light" or "dark"
defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "\\x90\\x90"
    subtitle = "Red Teaming & Security Research"
    #keywords = ""
    #copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    #readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home"
      logoHomeLink = "/"
    
  [[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "About"
    name       = "About"
    url        = "/about"

    # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:lorenzoinvidia[at]outlook.com"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/mattless_"

  [[params.social]]
    name = "github"
    url  = "https://github.com/lorenzoinvidia"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/lorenzo-invidia/"
